# Generated by Django 4.2.6 on 2024-01-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-search_date'],
            },
        ),
    ]
