# Generated by Django 5.0.1 on 2024-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.URLField(unique=True),
        ),
    ]
