# Generated by Django 5.0.1 on 2024-01-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0003_alter_newsarticle_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='source',
            new_name='source_url',
        ),
    ]
