# Generated by Django 5.0.1 on 2024-01-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0004_rename_source_newsarticle_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='source',
            new_name='source_url',
        ),
    ]
