# Generated by Django 5.0.1 on 2024-01-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0005_rename_source_searchhistory_source_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
