# Generated by Django 4.2.6 on 2024-01-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_sources',
            new_name='news_source',
        ),
    ]
