# Generated by Django 4.2.6 on 2024-01-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0008_rename_news_sources_news_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_source',
            new_name='newsSource',
        ),
    ]
