# Generated by Django 4.2.6 on 2024-01-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0009_rename_news_source_newssource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssource',
            old_name='link',
            new_name='url',
        ),
    ]
