# Generated by Django 4.2.6 on 2024-01-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0010_rename_link_newssource_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('adding_date', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_feed.newssource')),
            ],
        ),
    ]
