# Generated by Django 4.2.6 on 2024-01-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0011_sourcecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecategory',
            options={'ordering': ['-adding_date']},
        ),
        migrations.RenameField(
            model_name='sourcecategory',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sourcecategory',
            name='source_url',
        ),
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news_feed.sourcecategory'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(),
        ),
    ]
