# Generated by Django 4.2.6 on 2024-01-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0012_alter_sourcecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news_feed.sourcecategory'),
        ),
    ]
