# Generated by Django 4.2.6 on 2024-01-12 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0014_alter_newssource_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecategory',
            options={},
        ),
        migrations.RenameField(
            model_name='sourcecategory',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='title',
        ),
        migrations.AddField(
            model_name='sourcecategory',
            name='source_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_feed.newssource'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
