# Generated by Django 4.2.6 on 2024-01-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0015_alter_sourcecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcecategory',
            options={'ordering': ['-adding_date']},
        ),
        migrations.RemoveField(
            model_name='sourcecategory',
            name='source_url',
        ),
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_feed.sourcecategory'),
        ),
    ]
