# Generated by Django 4.2.6 on 2024-01-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0018_alter_newssource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
