# Generated by Django 4.2.6 on 2024-01-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0019_newssource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
