# Generated by Django 4.2.6 on 2024-01-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0022_alter_newssource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='category',
            field=models.ForeignKey(default='No Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='news_feed.sourcecategory'),
        ),
    ]
