# Generated by Django 4.2.6 on 2024-01-26 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_feed', '0024_sourcecategory_user_alter_newssource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sourcecategory',
            unique_together={('title', 'user')},
        ),
    ]
