# Generated by Django 4.2.6 on 2024-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0025_alter_sourcecategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(),
        ),
    ]
